server:
  port: 4444
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vani
    username: root
    password: Temp1234
  jpa:
   hibernate:
    ddl-auto: update

      
  application:
    name: coupon-service
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    
    service-url:
      defaultzone: http://localhost:8761/eureka
    

  

    
 
