server: 
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vani
    username: root
    password: Temp1234
  jpa:
   hibernate:
    ddl-auto: create

  application:
    name: coupon-service
  config:
    import:
    - optional:configserver:http://localhost:8888/
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultzone: http://localhost:8761/eureka


    

   
  
  

      

    

  

    
 