#spring.datasource.url=jdbc:mysql://localhost:3306/vani
#spring.datasource.username=root
#spring.datasource.password=Temp1234
#spring.jpa.hibernate.ddl-auto=create
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/vani
  username: root
  password: Temp1234
 jpa:
  hiberate:
   ddl-auto: create
 
 
 