server:
 port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vani
    username: root
    password: Temp1234
  jpa:
   hibernate:
    ddl-auto: update

  
  application:
    name: product-service

 

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
      
      
    
      
      
    
