server:
 port: 2222
 
#spring:
 #security:
  #user:
   #name: tom
   #password: tom@123
  
spring:
 datasource:
  url:  jdbc:mysql://localhost:3306/vani
  username: root
  password: Temp1234

 jpa: 
  hibernate:
   ddl-auto: update