#spring.datasource.url=jdbc:mysql://localhost:3306/vani
#spring.datasource.username=root
#spring.datasource.password=Temp1234
#spring.jpa.hibernate.ddl-auto=create
server:
 port: 3333
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/vani
   username: root
   password: Temp1234
  jpa:
    hibernate:
      ddl-auto: create
  show-sql:
  properties:
   hibernate:
    format_sql: true
    
Management:
endpoints: 
web:
base-path: /myactuator


exposure:
include:
- "*"

logging:
level:
com:
zensar: debug







#endpoint:
#shutdown:
#enabled: true


#info:
#build:
#enabled : true
#git:
#enabled : true
#env:
#enabled: true




#info:
#createdBy: VaniReddy.M
#modified: 22 jun 22