server:
  port: 8888
spring:
  cloud: 
    config:
      server:
        git:
          default-label: master
          uri: D:\\myConfig
  profiles:
    active: prod

  application: 
    name: config-server



    